# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "PyCon Zimbabwe 2018"
email: "zim.pycon@gmail.com"
description: "PyCon Zim is the conference for Python programmers in Zimbabwe"
baseurl: ""
url: "https://pyzim.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "Pyzim.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "PyConZim"
organizerAlternateName: "Python Zimbabwe User Group"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Python technology with passion."
organizerEmail: "python.zim@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://pyzim.org.zw"

# Head
metaKeywords: "event, python, django, programming, chrome, developers"
twitterAccount: "@pycon_zim"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://bit.ly/pyconzim-cfp"
c4sponsorsUrl: "http://bit.ly/spon-pyzim"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "News"}
 - {permalink: "/#tickets", text: "Tickets"}
 - {permalink: "/cod/", text: "Code Of Conduct"}
 - {permalink: "/#about", text: "About"}
 - {permalink: "/#partners", text: "Sponsors"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/#rockstar-speakers", text: "Speakers"}
 # - {permalink: "/team/", text: "Team"}
 # - {permalink: "/logistics/", text: "Logistics"}
 # - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "http://bit.ly/pyconzim-cfp", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "http://bit.ly/pyconzim-cfp", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "PyConZim 2018 <typeout> Harare"
eventDate: "19-20 October"
typeoutTextValues: '"", "", ""'
typeoutFallback: ""
heroButtons:
 - {link: "http://bit.ly/pyconzim-cfp", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About PyConZim"
aboutBlock:
 - {title: " Conference Day", image: "conference.jpg", text: "Full Day of talks on Python and related technologies presented by Zimbabwean & international speakers" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
 - {title: "Networking", image: "hackathon.jpg", text: "At PyConZim you will get a chance to meet and mingle with Africa's talented software developers" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "150", specialCharacter: "+", info: "participants", detail: "attending talks, training sessions and the CTF"}
 - {count: "2", specialCharacter: "+", info: "days", detail: "of Talks & Workshops"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from Zimbabwe and beyond"}
 - {count: "2", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Local & International speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Cresta Oasis Hotel"
eventLocationLink: "http://www.crestahotels.com/hotels/cresta-oasis"
eventStreetAddress: "124, Nelson Mandela Avenue, Harare"
eventAddressLocality: "Harare"
eventAddressLocalityRegion: "Harare"
eventPostalCode: "79000"
eventAddressCountry: "Harare"
eventStartTime: "2018-10-18T08:00"
eventDoorTime: "08:00"
eventEndTime: "2018-10-20T20:00"
eventPlaceCoordinates: "17.8992973,30.9547125"
mapCenterCoordinates: "17.8992973,30.9547125"
mapMobileCenterCoordinates: "17.8252, 31.0335"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Kinopalace Cinema"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "pyconzim"
twitterFeed: ""

# Partners Block
# organizersTitle: "Organizers"
# partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

#  call for sponsors
subscribeImage: "subscribe.jpg"
subscribeTitle: "Become a sponsor"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Support the event by becoming a sponsor. Flexible packages available to make your brand visible at Zimbabwe's biggest conference of software developers ."

# Tickets Block
ticketsTitle: "Buy your ticket now!"
ticketsInfo: "Tickets grant access to all conference sections, coffee breaks, and lunch. Accommodation is NOT included in the ticket price."
ticketsOffers:
 # -
 #  name: "Early Bird"
 #  price: "20"
 #  priceCurrency: "USD"
 #  ticketsNumber: ""
 #  ribbon: "-5%"
 #  buyButtonLink: "https://www.paynow.co.zw/Payment/Link/?q=c2VhcmNoPXB5dGhvbi56aW0lNDBnbWFpbC5jb20mYW1vdW50PTIwLjAwJnJlZmVyZW5jZT0mbD0x"
 #  buyButtonText: ""
 #  additionalInfo: "Buy your ticket before the 30th of July and get a discount "
 #  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
 #  validFrom: "2018-07-13T10:00"
 #  validThrough: "2018-07-30T23:59"
 #  disabled: true
 -
  name: "Regular"
  price: "32"
  priceCurrency: "USD"
  ticketsNumber: "TBA"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "https://www.paynow.co.zw/Payment/Link/?q=c2VhcmNoPXB5dGhvbi56aW0lNDBnbWFpbC5jb20mYW1vdW50PTI1LjAwJnJlZmVyZW5jZT0mbD0x"
  additionalInfo: "This ticket grants you full access to the conference"
  buyButtonText: " "
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2018-08-01T00:00"
  validThrough: "2018-10-20T23:59"
 -
  name: "Student"
  price: "20"
  priceCurrency: "USD"
  ticketsNumber: "TBA"
  buyButtonLink: "https://www.paynow.co.zw/Payment/Link/?q=c2VhcmNoPXB5dGhvbi56aW0lNDBnbWFpbC5jb20mYW1vdW50PTE1LjAwJnJlZmVyZW5jZT0mbD0x"
  buyButtonText: " "
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2108-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: false
  soldOutText: ""
 -
  name: "Corporate"
  price: "100"
  priceCurrency: "USD"
  ticketsNumber: ""
  buyButtonLink: "https://www.paynow.co.zw/Payment/Link/?q=c2VhcmNoPXB5dGhvbi56aW0lNDBnbWFpbC5jb20mYW1vdW50PTEwMC4wMCZyZWZlcmVuY2U9Jmw9MQ%3d%3d"
  buyButtonText: " "
  additionalInfo: "Buy this ticket if your company is paying for you. This ticket grants you access to the talks & workshops"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2018-07-16T10:00"
  validThrough: "2018-10-20T23:59"
  soldOut: false
  soldOutText: "Sold Out"
 -
  name: "Workshop/Tutorial"
  price: "12"
  priceCurrency: "USD"
  ticketsNumber: ""
  buyButtonLink: "https://www.paynow.co.zw/Payment/Link/?q=c2VhcmNoPXB5dGhvbi56aW0lNDBnbWFpbC5jb20mYW1vdW50PTEyLjAwJnJlZmVyZW5jZT0mbD0x"
  buyButtonText: " "
  additionalInfo: "Buy this ticket if you want to attend the workshops and training sessions only on Saturday."
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2018-07-16T10:00"
  validThrough: "2018-10-20T23:59"
  soldOut: false
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=pycon_zim", icon: "twitter"}
 - {link: "https://facebook.com/pyconzim", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://groups.google.com", text: "Zimbabwe Python Users Group"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:zim.pycon@gmail.com", text: "zim.pycon@gmail.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "pyconzim"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "17.8995548,30.9545836"
logisticsMapMobileCenterCoordinates: "17.8995548,30.9545836"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Harare"
directionDetailsCards:
 - {title: "From the Airport", information: 'Robert Mugabe Internationa Airport is located 15 km south of Harares central business district and acts as the link between Harare and the outside world. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://www.caaz.co.zw/">airport website</a>.'}
 - {title: "Public Transit", information: 'You can find your way in Harare using public transport or taxis.'}
 - {title: "Hotels", information: 'Harare has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "http://brontehotel.com/", text: "Bronte Garden Hotel"}
     - {link: "http://queensgatebaines.com/", text: "Queensgate & Baines"}
     - {link: "http://www.crestahotels.com/hotels/cresta-oasis", text: "Cresta Oasis"}
     - {link: "http://www.crestahotels.com/hotels/cresta-jameson", text: "Cresta Jameson"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.840696, 24.028754"
